name: SipX MSVS Windows build
on:
  push:
    #branches: [ $default-branch ]
  pull_request:
    # all PRs for now
    #branches: [ $default-branch ]

jobs:
  # Label of the runner job
  sipx-MSVS2019-Windows10-build:

    runs-on: windows-2019
    
    steps:
    
      - name: check env
        run: |
          $Env:Path
          $Env:Path = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools; $Env:Path"
          $env:Path
          echo $SHELL
          python3 --version

      - name: env cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsMSBuildCmd.bat"
          echo %PATH%
          systeminfo | findstr /B /C:"OS Name" /B /C:"OS Version"
        shell: cmd

      - name: checkout ${{ github.ref }}
        # Downloads a copy of the code in your repository before running CI tests
        uses: actions/checkout@v3
        with:
          repository: sipXtapi/sipXtapi
          
      - name: MSVS build
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsMSBuildCmd.bat"  -arch=x64 -winsdk="10.0.19041.0"
          echo %PATH%
          #VsMSBuildCmd.bat -arch=x64 -winsdk="10.0.19041.0"
          dir
          msbuild.exe sipX-msvc16.sln /t:Clean,Build /p:Configuration=Release /p:Platform=x64
        shell: cmd

      
