name: SipX MSVS Windows build
on:
  push:
    #branches: [ $default-branch ]
  pull_request:
    # all PRs for now
    #branches: [ $default-branch ]

jobs:
  # Label of the runner job
  sipx-build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            solution_file: sipX-msvc16.sln
            msvs_year: 2019
            prog_root: \Program Files (x86)
          - os: windows-2022
            solution_file: sipX-msvc17.sln
            msvs_year: 2022
            prog_root: \Program Files

    runs-on: ${{ matrix.os }}
    
    steps:
    
      - name: check env
        run: |
          $Env:Path
          $Env:Path = "C:${{ matrix.prog_root }}\Microsoft Visual Studio\${{ matrix.msvs_year }}\Enterprise\Common7\Tools; $Env:Path"
          $env:Path
          echo $SHELL
          python3 --version

      - name: env cmd
        run: |
          systeminfo | findstr /B /C:"OS Name" /B /C:"OS Version"
          call "C:${{ matrix.prog_root }}\Microsoft Visual Studio\${{ matrix.msvs_year }}\Enterprise\Common7\Tools\VsMSBuildCmd.bat"
          echo %PATH%
        shell: cmd

      - name: checkout ${{ github.ref }}
        # Downloads a copy of the code in your repository before running CI tests
        uses: actions/checkout@v3
        with:
          repository: sipXtapi/sipXtapi
          
      #VsMSBuildCmd.bat -arch=x64 -winsdk="10.0.19041.0"
      - name: MSVS ${{ matrix.msvs_year }} build
        run: |
          call "C:${{ matrix.prog_root }}\Microsoft Visual Studio\${{ matrix.msvs_year }}\Enterprise\Common7\Tools\VsMSBuildCmd.bat"  -arch=x64
          echo %PATH%
          dir
          msbuild.exe ${{ matrix.solution_file }} /t:Clean,Build /p:Configuration=Release /p:Platform=x64
        shell: cmd

      
